website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__, static_url_path='/static')
    app.config['SECRET_KEY'] = 'testing'

    from .views import views
    # from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    # app.register_blueprint(auth, url_prefix='/')

    return app

website/views.py
from flask import Blueprint, render_template, session, request, redirect, url_for, flash, jsonify

from vertexFunction import vertexCall


views = Blueprint("views", __name__)

def checkSession():
    if 'sidebar_state' not in session:
        session['sidebar_state'] = 'open'

@views.route('/')
def index():
    if 'sidebar_state' not in session:
        session['sidebar_state'] = 'open'
    return redirect(url_for('views.home'))

@views.route('/home', methods=['GET'])
def home():
    return render_template('home.html', current_page='home')

@views.route('/home-backup', methods=['GET'])
def homebackup():
    return render_template('home-backup.html', current_page='home-backup')

@views.route('/syntax', methods=['GET'])
def syntax():
    checkSession()
    return render_template('syntax.html', current_page='syntax')

@views.route('/comments', methods=['GET'])
def comments():
    checkSession()
    return render_template('comments.html', current_page='comments')

@views.route('/variables', methods=['GET'])
def variables():
    checkSession()
    return render_template('variables.html', current_page='variables')

@views.route('/variableNames', methods=['GET'])
def variableNames():
    checkSession()
    return render_template('variableNames.html', current_page='variableNames')

@views.route('/assignMultipleValues', methods=['GET'])
def assignMultipleValues():
    checkSession()
    return render_template('assignMultipleValues.html', current_page='assignMultipleValues')

@views.route('/outputVariables', methods=['GET'])
def outputVariables():
    checkSession()
    return render_template('outputVariables.html', current_page='outputVariables')

@views.route('/datatypes', methods=['GET'])
def datatypes():
    checkSession()
    return render_template('datatypes.html', current_page='datatypes')

@views.route('/numbers', methods=['GET'])
def numbers():
    checkSession()
    return render_template('numbers.html', current_page='numbers')

@views.route('/casting', methods=['GET'])
def casting():
    checkSession()
    return render_template('casting.html', current_page='casting')


@views.route('/pythonStrings', methods=['GET'])
def pythonStrings():
    checkSession()
    return render_template('pythonStrings.html', current_page='pythonStrings')

@views.route('/slicingStrings', methods=['GET'])
def slicingStrings():
    checkSession()
    return render_template('slicingStrings.html', current_page='slicingStrings')

@views.route('/modifyStrings', methods=['GET'])
def modifyStrings():
    checkSession()
    return render_template('modifyStrings.html', current_page='modifyStrings')

@views.route('/concatenateStrings', methods=['GET'])
def concatenateStrings():
    checkSession()
    return render_template('concatenateStrings.html', current_page='concatenateStrings')

@views.route('/formatStrings', methods=['GET'])
def formatStrings():
    checkSession()
    return render_template('formatStrings.html', current_page='formatStrings')

@views.route('/escapeStrings', methods=['GET'])
def escapeStrings():
    checkSession()
    return render_template('escapeStrings.html', current_page='escapeStrings')

@views.route('/stringMethods', methods=['GET'])
def stringMethods():
    checkSession()
    return render_template('stringMethods.html', current_page='stringMethods')

@views.route('/booleans', methods=['GET'])
def booleans():
    checkSession()
    return render_template('booleans.html', current_page='booleans')

@views.route('/operators', methods=['GET'])
def operators():
    checkSession()
    return render_template('operators.html', current_page='operators')

@views.route('/tuples', methods=['GET'])
def tuples():
    checkSession()
    return render_template('tuples.html', current_page='tuples')

@views.route('/ifelse', methods=['GET'])
def ifelse():
    checkSession()
    return render_template('ifelse.html', current_page='ifelse')

@views.route('/whileloops', methods=['GET'])
def whileloops():
    checkSession()
    return render_template('whileloops.html', current_page='whileloops')

@views.route('/forloops', methods=['GET'])
def forloops():
    checkSession()
    return render_template('forloops.html', current_page='forloops')

@views.route('/functions', methods=['GET'])
def functions():
    checkSession()
    return render_template('functions.html', current_page='functions')

@views.route('/lambdas', methods=['GET'])
def lambdas():
    checkSession()
    return render_template('lambdas.html', current_page='lambdas')

@views.route('/toggle_sidebar')
def toggle_sidebar():
    return jsonify({'sidebar_state': session.get('sidebar_state', 'collapsed')})

@views.route('/toggleSidebar')
def toggleSidebar():
    # # Toggle sidebar state between 'open' and 'collapsed'
    if session['sidebar_state'] == 'open':
        session['sidebar_state'] = 'collapsed'
    else:
        session['sidebar_state'] = 'open'
    return jsonify({'sidebar_state': session.get('sidebar_state', 'collapsed')})

@views.route('/askVertex', methods=['POST'])
def askVertex():
    message = request.json.get('message')
    if message:
        reply = vertexCall(message)
        return jsonify({'reply': reply}), 200
    else:
        return jsonify({'error': 'No message provided'}), 400


# ? do we need this
@views.route('/chat', methods=['GET', 'POST'])
def chat():
    if request.method == 'POST':
        user_text = request.form['user_text']
        print("User input:", user_text)
    return render_template('chat.html')

website/templates/concatenateStrings.html
{% extends "base.html" %}

{% block title %}String Concatenation{% endblock %}

{% block content %}

<div class="">
    <div class="header space-y-3 py-4 px-5">
        <p class="text-4xl font-bold">Python - String Concatenation</p>

        <div style="margin-bottom: 0%;">
            <a href="{{ url_for('views.modifyStrings') }}" class="button-link ">
                <button class="btn btn-primary">Previous</button>
            </a>
            <a href="{{ url_for('views.formatStrings') }}" class="button-link btn-primary float-right">
                <button class="btn btn-primary">Next</button>
            </a>
        </div>
    </div>
    <div class="px-12 pb-4">
        <hr class="my-4">
        <div class="content-1 space-y-3">
            <div class="content title space-y-3">
                <div class="text-3xl">String Concatenation</div><br>
                <p>To join, or merge, two strings, you can employ the + operator.</p>
            </div>
            <div class="rounded-lg bg-slate-300 p-3 w-full h-auto mt-2">
                <div class="text-xl mb-2">Example</div>
                <div>Merge variable <span class="text-red-600">a</span> with variable <span
                        class="text-red-600">b</span> into variable c:</div>
                <div class="bg-white w-full p-2 pl-3 flex flex-col relative">
                    <div>a = <span class="text-red-600"> "Hello"</span>
                    </div>
                    <div>b = <span class="text-red-600"> "Hello"</span>
                    </div>
                    <div>c = a + b
                    </div>
                    <div><span class="text-blue-600"> print</span>(c)
                    </div>
                    <div class="absolute top-0 left-0 bg-green-300 p-0.5 h-full"></div>

                </div>

            </div>
            <br>
            <div class="rounded-lg bg-slate-300 p-3 w-full h-auto mt-2">
                <div class="text-xl mb-2">Example</div>
                <div>To include a space between them, append a <span class="text-red-600">" "</span>:</div>
                <div class="bg-white w-full p-2 pl-3 flex flex-col relative">
                    <div>a = <span class="text-red-600"> "Hello"</span>
                    </div>
                    <div>b = <span class="text-red-600"> "Hello"</span>
                    </div>
                    <div>c = a + <span class="text-red-600">" "</span> + b
                    </div>
                    <div><span class="text-blue-600"> print</span>(c)
                    </div>
                    <div class="absolute top-0 left-0 bg-green-300 p-0.5 h-full"></div>

                </div>

            </div>
            <div style="margin-bottom: 0%;">
                <a href="{{ url_for('views.modifyStrings') }}" class="button-link ">
                    <button class="btn btn-primary">Previous</button>
                </a>
                <a href="{{ url_for('views.formatStrings') }}" class="button-link btn-primary float-right">
                    <button class="btn btn-primary">Next</button>
                </a>
            </div>

        </div>
        <hr class="my-4">
        <h2 class="text-3xl">Think Yourself</h2>
        <br>
        <div class="content-3 space-y-3 rounded-lg bg-black p-4">
            <h2 class="text-3xl text-white">What do you think is the output?</h2>
            <div class="bg-white p-2 pl-3 flex flex-col relative">
                <div>words = [<span class="text-red-600"> "This"</span>, <span class="text-red-600"> "is"</span>, <span
                        class="text-red-600"> "a"</span>, <span class="text-red-600"> "sentence"</span>]
                </div>
                <div>sentence = <span class="text-red-600">" "</span>.<span class="text-blue-600">join</span>(words)
                </div>
                <div><span class="text-blue-600"> print</span>(sentence)
                </div>
                <div class="absolute top-0 left-0 bg-green-300 p-0.5 h-full"></div>
            </div>
            <button type="button"
                onclick="sendChat(`explain the output of this python ode in short words = [ 'This', 'is', 'a', 'sentence'] sentence = ' '.join(words) print(sentence) `)"
                class="btn btn-success mt-3">I Don't Know?</button>
        </div>
    </div>
    {% endblock %}

website/templates/datatypes.html
{% extends "base.html" %}

{% block title %}Data Types{% endblock %}

{% block content %}
<style>
    td {
        padding: 8px;
    }

    .border-table-datatype tr:nth-child(even) {
        background-color: #E7E9EB;
    }

    .border-table {
        margin: 20px 0;
        border: 1px solid #ccc;
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
        display: table;
    }

    .border-table-datatype th,
    .border-table-datatype td {
        padding: 8px 8px;
        display: table-cell;
        text-align: left;
        vertical-align: top;
        padding-left: 16px;
    }
</style>
<div class="">
    <div class="header space-y-3 py-4 px-5">
        <p class="text-4xl font-bold">Python Data Types</p>
        <div style="margin-bottom: 0%;">
            <a href="{{ url_for('views.outputVariables') }}" class="button-link ">
                <button class="btn btn-primary">Previous</button>
            </a>
            <a href="{{ url_for('views.numbers') }}" class="button-link btn-primary float-right">
                <button class="btn btn-primary">Next</button>
            </a>
        </div>
    </div>
    <div class="px-12 pb-4">
        <hr class="my-4">
        <div class="content-1 space-y-3">
            <div class="content title">
                <div class="text-3xl">Built-in Data Types</div><br>
                <p>Data types are crucial concepts in programming.</p>
                <p>Variables have the capability to store data of varying types, each type enabling different
                    functionalities.</p>
                <p>Python includes the following built-in data types by default, categorized as follows:</p>
            </div>
            <table class="">
                <tr>
                    <td style="width:160px;">Text Type:</td>
                    <td><code class="p-data">str</code></td>
                </tr>
                <tr>
                    <td>Numeric Types:</td>
                    <td><code class="p-data">int</code>, <code class="p-data">float</code>,
                        <code class="p-data">complex</code>
                    </td>
                </tr>
                <tr>
                    <td>Sequence Types:</td>
                    <td><code class="p-data">list</code>, <code class="p-data">tuple</code>,
                        <code class="p-data">range</code>
                    </td>
                </tr>
                <tr>
                    <td>Mapping Type:</td>
                    <td><code class="p-data">dict</code></td>
                </tr>
                <tr>
                    <td>Set Types:</td>
                    <td><code class="p-data">set</code>, <code class="p-data">frozenset</code></td>
                </tr>
                <tr>
                    <td>Boolean Type:</td>
                    <td><code class="p-data">bool</code></td>
                </tr>
                <tr>
                    <td>Binary Types:</td>
                    <td><code class="p-data">bytes</code>, <code class="p-data">bytearray</code>,
                        <code class="p-data">memoryview</code>
                    </td>
                </tr>
                <tr>
                    <td>None Type:</td>
                    <td><code class="p-data">NoneType</code></td>
                </tr>
            </table>
        </div>
        <hr class="my-4">
        <div class="content-2 space-y-3">
            <div class="content title">
                <div class="text-3xl">Getting The Data Type</div><br>
                <div class="space-y-2">
                    <p>To retrieve the data type of any object, you can utilize the <span
                            class="p-data text-red-600">type()</span> function.</p>
                </div>
            </div>
            <div class=" rounded-lg bg-slate-300 p-3 w-full h-auto mt-2">
                <div class="text-xl mb-2">Example</div>
                <div class="text-md mb-3">Display the data type of variable x:</div>
                <div class="bg-white w-full p-2 pl-3 flex flex-col relative">
                    <div class="text-red-600"><span class="text-black">x = </span>5</div>
                    <div class="text-blue-600">print<span class="text-black">&#40;</span>type<span
                            class="text-black">&#40;x&#41;&#41;</span></div>

                    <div class="absolute top-0 left-0 bg-green-300 p-0.5 h-full"></div>
                </div>
            </div>
        </div>
        <hr class="my-4">
        <div class="content-2 space-y-3">
            <div class="content title">
                <div class="text-3xl">Setting the Data Type</div><br>
                <div class="space-y-2">
                    <p>In Python, the data type is determined when you assign a value to a variable.</p>
                </div>
            </div>
            <table class="border-table border-table-datatype">
                <tr>
                    <th style="min-width:350px">Example</th>
                    <th>Data Type</th>
                </tr>
                <tr>
                    <td>x = &quot;Hello World&quot;</td>
                    <td>str</td>

                </tr>
                <tr>
                    <td>x = 220</td>
                    <td>int</td>

                </tr>
                <tr>
                    <td>x = 312.5</td>
                    <td>float</td>

                </tr>
                <tr>
                    <td>x = 1j</td>
                    <td>complex</td>

                </tr>
                <tr>
                    <td>x = [&quot;A&quot;, &quot;B&quot;, &quot;D&quot;]</td>
                    <td>list</td>

                </tr>
                <tr>
                    <td>x = (&quot;A&quot;, &quot;B&quot;, &quot;C&quot;)</td>
                    <td>tuple</td>

                </tr>
                <tr>
                    <td>x = range(10)</td>
                    <td>range</td>

                </tr>
                <tr>
                    <td>x = {&quot;Name&quot; : &quot;Ian&quot;, &quot;Age&quot; : 21}</td>
                    <td>dict</td>

                </tr>
                <tr>
                    <td>x = {&quot;A&quot;, &quot;B&quot;, &quot;C&quot;}</td>
                    <td>set</td>

                </tr>
                <tr>
                    <td>x = frozenset({&quot;A&quot;, &quot;B&quot;, &quot;C&quot;})</td>
                    <td>frozenset</td>

                </tr>
                <tr>
                    <td>x = False</td>
                    <td>bool</td>

                </tr>
                <tr>
                    <td>x = b&quot;Hello&quot;</td>
                    <td>bytes</td>

                </tr>
                <tr>
                    <td>x = bytearray(5)</td>
                    <td>bytearray</td>

                </tr>
                <tr>
                    <td>x = memoryview(bytes(5))</td>
                    <td>memoryview</td>

                </tr>
                <tr>
                    <td>x = None</td>
                    <td>NoneType</td>

                </tr>
            </table>
        </div>
        <hr class="my-4">
        <div class="content-2 space-y-3">
            <div class="content title">
                <div class="text-3xl">Setting the Specific Data Type</div><br>
                <div class="space-y-2">
                    <p>If you wish to specify the data type, you can employ the following constructor functions:</p>
                </div>
            </div>
            <table class="border-table border-table-datatype">
                <tr>
                    <th style="min-width:350px">Example</th>
                    <th>Data Type</th>

                </tr>
                <tr>
                    <td>x = str(&quot;Hello World&quot;)</td>
                    <td>str</td>

                </tr>
                <tr>
                    <td>x = int(220)</td>
                    <td>int</td>

                </tr>
                <tr>
                    <td>x = float(212.5)</td>
                    <td>float</td>

                </tr>
                <tr>
                    <td>x = complex(1j)</td>
                    <td>complex</td>

                </tr>
                <tr>
                    <td>x = list((&quot;A&quot;, &quot;B&quot;, &quot;C&quot;))</td>
                    <td>list</td>
                </tr>
                <tr>
                    <td>x = tuple((&quot;A&quot;, &quot;B&quot;, &quot;C&quot;))</td>
                    <td>tuple</td>
                </tr>
                <tr>
                    <td>x = range(6)</td>
                    <td>range</td>
                </tr>
                <tr>
                    <td>x = dict(name=&quot;Ian&quot;, Age=36)</td>
                    <td>dict</td>
                </tr>
                <tr>
                    <td>x = set((&quot;A&quot;, &quot;B&quot;, &quot;C&quot;))</td>
                    <td>set</td>
                </tr>
                <tr>
                    <td>x = frozenset((&quot;A&quot;, &quot;B&quot;, &quot;C&quot;))</td>
                    <td>frozenset</td>
                </tr>
                <tr>
                    <td>x = bool(5)</td>
                    <td>bool</td>
                </tr>
                <tr>
                    <td>x = bytes(5)</td>
                    <td>bytes</td>
                </tr>
                <tr>
                    <td>x = bytearray(5)</td>
                    <td>bytearray</td>
                </tr>
                <tr>
                    <td>x = memoryview(bytes(5))</td>
                    <td>memoryview</td>
                </tr>
            </table>
            <div style="margin-bottom: 0%;">
                <a href="{{ url_for('views.outputVariables') }}" class="button-link ">
                    <button class="btn btn-primary">Previous</button>
                </a>
                <a href="{{ url_for('views.numbers') }}" class="button-link btn-primary float-right">
                    <button class="btn btn-primary">Next</button>
                </a>
            </div>
        </div>
        <hr class="my-4">
        <div class="content-2 space-y-3">
            <h2 class="text-3xl">Think Yourself</h2>
            <br>
            <div class="content-3 space-y-3 rounded-lg bg-black p-4">
                <h2 class="text-3xl text-white">What is the Data Type?</h2>
                <div class="bg-white p-2 pl-3 flex flex-col relative">
                    <div class="text-black">x = range&#40;1, 10&#41;</div>
                    <div class="text-black"><span class="text-blue-600">print</span>&#40;type&#40;x&#41;&#41;</div>
                    <div class="absolute top-0 left-0 bg-green-300 p-0.5 h-full"></div>
                </div>
                <button type="button"
                    onclick="sendChat(`explain the concept of this python code in short    x = range(1, 10)      print(type(x))`)"
                    class="btn btn-success mt-3">I Don't Know?</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/escapeStrings.html
{% extends "base.html" %}

{% block title %}Escape Characters{% endblock %}

{% block content %}

<style>
    td {
        padding: 8px;
    }

    .p-data {
        background-color: rgba(222, 222, 222, 0.3);
        padding-left: 4px;
        padding-right: 4px;
    }

    .border-table-datatype tr:nth-child(even) {
        background-color: #E7E9EB;
    }

    .border-table {
        margin: 20px 0;
        border: 1px solid #ccc;
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
        display: table;
    }

    .border-table-datatype th,
    .border-table-datatype td {
        padding: 8px 8px;
        display: table-cell;
        text-align: left;
        vertical-align: top;
        padding-left: 16px;
    }
</style>

<div class="">
    <div class="header space-y-3 py-4 px-5">
        <p class="text-4xl font-bold">Python - Escape Characters</p>

        <div style="margin-bottom: 0%;">
            <a href="{{ url_for('views.formatStrings') }}" class="button-link ">
                <button class="btn btn-primary">Previous</button>
            </a>
            <a href="{{ url_for('views.stringMethods') }}" class="button-link btn-primary float-right">
                <button class="btn btn-primary">Next</button>
            </a>
        </div>
    </div>
    <div class="px-12 pb-4">
        <hr class="my-4">
        <div class="content-1 space-y-3">
            <div class="content title space-y-3">
                <div class="text-3xl">Escape Character</div><br>
                <div class="space-y-3">
                    <p>To insert characters that are illegal in a string, use an escape character.

                    </p>
                    <p>An escape character is a backslash \ followed by the character you want to insert.

                    </p>
                    <p>An example of an illegal character is a double quote inside a string that is surrounded by double
                        quotes:

                    </p>
                </div>
            </div>
            <div class="rounded-lg bg-red-200 p-3 w-full h-auto mt-2">
                <div class="text-xl mb-2">Example</div>
                <div>You will get an error if you use double quotes inside a string that is surrounded by double quotes:

                </div>
                <div class="bg-white w-full p-2 pl-3 flex flex-col relative">

                    <div>txt = <span class="text-red-600">"We are the so-called "</span>Vikings <span
                            class="text-red-600">" from the north."</span>
                    </div>
                    <div class="absolute top-0 left-0 bg-red-600 p-0.5 h-full"></div>

                </div>

            </div>
            <div>To fix this problem, use the escape character \":</div>
            <div class="rounded-lg bg-slate-300 p-3 w-full h-auto mt-2">
                <div class="text-xl mb-2">Example</div>
                <div>The escape character allows you to use double quotes when you normally would not be allowed:</div>
                <div class="bg-white w-full p-2 pl-3 flex flex-col relative">
                    <div>txt = <span class="text-red-600">"We are the so-called \"</span>Vikings \<span
                            class="text-red-600">" from the north."</span>
                    </div>

                    <div class="absolute top-0 left-0 bg-green-300 p-0.5 h-full"></div>

                </div>

            </div>
        </div>

        <hr class="my-4">
        <div class="content-1 space-y-3">
            <table class="border-table border-table-datatype">
                <tr>
                    <th style="min-width:350px">Code</th>
                    <th>Result</th>
                    <!-- <th style="width:90px">Try it</th> -->
                </tr>
                <tr>
                    <td>\'</td>
                    <td>Single Quote
                    </td>
                    <!-- <td><a target="_blank" class="w3-btn btnsmall btnsmall" -->
                    <!-- href="trypython.asp?filename=demo_type_str">Try it &raquo;</a></td> -->
                </tr>
                <tr>
                    <td>\\</td>
                    <td>Backslash</td>
                    <!-- <td><a target="_blank" class="w3-btn btnsmall btnsmall"
                            href="trypython.asp?filename=demo_type_int">Try it &raquo;</a></td> -->
                </tr>
                <tr>
                    <td>\n </td>
                    <td>New Line
                    </td>
                    <!-- <td><a target="_blank" class="w3-btn btnsmall btnsmall"
                            href="trypython.asp?filename=demo_type_float">Try it &raquo;</a></td> -->
                </tr>
                <tr>
                    <td>\r </td>
                    <td>Carriage Return
                    </td>
                    <!-- <td><a target="_blank" class="w3-btn btnsmall btnsmall"
                            href="trypython.asp?filename=demo_type_complex">Try it &raquo;</a></td> -->
                </tr>
                <tr>
                    <td>\t </td>
                    <td>liTabst</td>
                    <!-- <td><a target="_blank" class="w3-btn btnsmall btnsmall"
                            href="trypython.asp?filename=demo_type_list">Try it &raquo;</a></td> -->
                </tr>
                <tr>
                    <td>\b</td>
                    <td>Backspace</td>
                    <!-- <td><a target="_blank" class="w3-btn btnsmall btnsmall"
                            href="trypython.asp?filename=demo_type_tuple">Try it &raquo;</a></td> -->
                </tr>
                <tr>
                    <td>\f</td>
                    <td>Form Feed </td>
                    <!-- <td><a target="_blank" class="w3-btn btnsmall btnsmall"
                            href="trypython.asp?filename=demo_type_range">Try it &raquo;</a></td> -->
                </tr>
                <tr>
                    <td>\ooo </td>
                    <td>Octal value
                    </td>
                    <!-- <td><a target="_blank" class="w3-btn btnsmall btnsmall"
                            href="trypython.asp?filename=demo_type_dict">Try it &raquo;</a></td> -->
                </tr>
                <tr>
                    <td>\xhh</td>
                    <td>Hex value</td>
                    <!-- <td><a target="_blank" class="w3-btn btnsmall btnsmall"
                            href="trypython.asp?filename=demo_type_set">Try it &raquo;</a></td> -->
                </tr>

            </table>
        </div>
        <div style="margin-bottom: 0%;">
            <a href="{{ url_for('views.formatStrings') }}" class="button-link ">
                <button class="btn btn-primary">Previous</button>
            </a>
            <a href="{{ url_for('views.stringMethods') }}" class="button-link btn-primary float-right">
                <button class="btn btn-primary">Next</button>
            </a>
        </div>
    </div>

    <!-- Chat Content -->
    <!-- <div class="right-content w-1/2 relative" style="height: calc(100vh - 4rem);">  -->
    {% endblock %}